name: Continuous
on:
  push:
    branches:
      - master
permissions:
  contents: read
  id-token: write
jobs:
  all:
    runs-on: macos-11
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install and setup casks
        run: |
          brew install --cask packages vmware-fusion
          sh ./hack/kickstart-vmware.sh '${{ secrets.VMWARE_FUSION_SERIAL_NUMBER }}'
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      - name: install and setup formulae
        run: |
          brew install packer skopeo
          sh ./hack/unttify-skopeo.sh
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      - name: make all
        run: make
        env:
          PACKER_LOG: '1'
          VAGRANT_LOG: debug
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ecr-public
      - name: make docker
        run: |
          aws ecr-public get-login-password | skopeo login -u AWS --password-stdin public.ecr.aws
          make "TAG=$(git describe --dirty --broken --always)" -C oci push
          make "TAG=$(git describe --dirty --broken --always)" -C oci latest
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
