name: Continuous
on: push
permissions:
  contents: read
  id-token: write
jobs:
  all:
    runs-on: macos-11
    steps:
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/macbox
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install and setup casks
        run: |
          brew install --cask packages vmware-fusion
          sh ./hack/kickstart-vmware.sh '${{ secrets.VMWARE_FUSION_SERIAL_NUMBER }}'
      - name: install and setup formulae
        run: |
          brew install packer skopeo
          sh ./hack/unttify-skopeo.sh
          aws ecr-public get-login-password | skopeo login -u AWS --password-stdin public.ecr.aws
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - run: make
        env:
          PACKER_LOG: '1'
          VAGRANT_LOG: debug
      - run: make "TAG=$(git describe --dirty --broken --always)" -C oci push
      - run: make "TAG=$(git describe --dirty --broken --always)" -C oci latest
        if: github.ref == 'refs/heads/master'
