name: Continuous
on:
  push:
    branches:
      - master
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  all:
    runs-on: macos-11
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      PACKER_LOG: '1'
      VAGRANT_LOG: debug
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install unttify
        run: cp ./hack/unttify.py /usr/local/bin/unttify
      - name: install and setup casks
        run: |
          brew install --cask packages vmware-fusion
          sh ./hack/kickstart-vmware.sh '${{ secrets.VMWARE_FUSION_SERIAL_NUMBER }}'
      - name: install and setup formulae
        run: |
          brew install --formula packer parallel skopeo
          sh ./hack/cite-parallel.sh
          sh ./hack/unttify-skopeo.sh
      - name: purge frameworks
        run: sudo ./hack/purge-frameworks.sh
      - name: make all
        run: make
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ecr-public
      - name: docker login
        run: |
          # skopeo login -u '${{ secrets.DOCKER_USER }}' -p '${{ secrets.DOCKER_PASS }}' docker.io
          skopeo login -u '${{ github.actor }}' -p '${{ github.token }}' ghcr.io
          aws ecr-public get-login-password | skopeo login -u AWS --password-stdin public.ecr.aws
      - name: docker push
        shell: '/usr/bin/env parallel --lb :::: {0}'
        run: |
          # make 'IMAGE_REGISTRY=docker.io' 'IMAGE_REPOSITORY=inloco/macbox' -C oci push
          make 'IMAGE_REGISTRY=ghcr.io' 'IMAGE_REPOSITORY=inloco/macbox' -C oci push
          make 'IMAGE_REGISTRY=public.ecr.aws' 'IMAGE_REPOSITORY=incognia/macbox' -C oci push
      - name: docker tag
        shell: '/usr/bin/env parallel --lb :::: {0}'
        run: |
          # make 'IMAGE_REGISTRY=docker.io' 'IMAGE_REPOSITORY=inloco/macbox' -C oci latest
          make 'IMAGE_REGISTRY=ghcr.io' 'IMAGE_REPOSITORY=inloco/macbox' -C oci latest
          make 'IMAGE_REGISTRY=public.ecr.aws' 'IMAGE_REPOSITORY=incognia/macbox' -C oci latest
